---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-subscriptions
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: maas-workloads
  destination:
    name: in-cluster
    namespace: models-as-a-service
  sources:
    - repoURL: https://github.com/javo8a/rhoai-platform.git
      targetRevision: main
      path: charts/maas-subscriptions
      helm:
        valueFiles:
          - $workloads/clusters/cluster-6bmxk.6bmxk.sandbox5237.opentlc.com/values/maas-subscriptions/values.yaml
    - repoURL: https://github.com/javo8a/rhoai-workloads.git
      targetRevision: main
      ref: workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
