---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: rhoai-platform
  destination:
    name: in-cluster
    namespace: redhat-ods-applications
  source:
    path: charts/maas-postgres
    repoURL: https://github.com/javo8a/rhoai-platform.git
    targetRevision: main
    helm:
      valueFiles:
        - ../../clusters/cluster-6bmxk.6bmxk.sandbox5237.opentlc.com/cluster.yaml
        - ../../clusters/cluster-6bmxk.6bmxk.sandbox5237.opentlc.com/platform/values/maas-postgres/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
