---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-enablement
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: rhoai-platform
  destination:
    name: in-cluster
    namespace: openshift-nfd
  source:
    path: charts/nvidia-gpu-enablement
    repoURL: https://github.com/javo8a/rhoai-platform.git
    targetRevision: main
    helm:
      valueFiles:
        - ../../clusters/cluster-6bmxk.6bmxk.sandbox5237.opentlc.com/cluster.yaml
        - ../../clusters/cluster-6bmxk.6bmxk.sandbox5237.opentlc.com/platform/values/nvidia-gpu-enablement/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
