---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leaderworkerset
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: rhoai-platform
  destination:
    name: in-cluster
    namespace: openshift-lws-operator
  source:
    path: charts/leaderworkerset
    repoURL: https://github.com/javo8a/rhoai-platform.git
    targetRevision: main
    helm:
      valueFiles:
        - ../../clusters/cluster-8h7g4.8h7g4.sandbox966.opentlc.com/cluster.yaml
        - ../../clusters/cluster-8h7g4.8h7g4.sandbox966.opentlc.com/platform/values/leaderworkerset/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
