---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: rhoai-platform
  destination:
    name: in-cluster
    namespace: cert-manager-operator
  source:
    path: charts/cert-manager
    repoURL: https://github.com/javo8a/rhoai-platform.git
    targetRevision: main
    helm:
      valueFiles:
        - ../../clusters/example.cluster.opentlc.com/cluster.yaml
        - ../../clusters/example.cluster.opentlc.com/platform/values/cert-manager/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
