---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: rhoai-platform
  destination:
    name: in-cluster
    namespace: openshift-operators
  source:
    path: charts/observability-operators
    repoURL: https://github.com/javo8a/rhoai-platform.git
    targetRevision: main
    helm:
      valueFiles:
        - ../../clusters/example.cluster.opentlc.com/cluster.yaml
        - ../../clusters/example.cluster.opentlc.com/platform/values/observability-operators/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
